# Generated by Django 3.2 on 2022-09-11 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0002_auto_20220911_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedData',
            new_name='JsonData',
        ),
    ]
